[workspace]
members = [
	"Element/Echo",
	"Element/Mountain",
	# "Element/Rest",
	"Element/River",
	"Element/Sun",

	"Dependency/Land/Cargo/Maintain",
]
resolver = "2"
exclude = [
	"Dependency/Land/Dependency/Editor/cli",
	"Dependency/Land/Dependency/Editor/build/win32",
]

[workspace.package]
authors = ["ğŸ–‹ï¸â€Sourceâ€â€”â€ğŸ‘ğŸ»â€Openâ€â€” <Source/Open@Editor.Land>"]
documentation = "HTTPS://Documentation.Editor.Land"
edition = "2021"
homepage = "HTTPS://Editor.Land/"
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "https://github.com/CodeEditorLand/EcoSystem"

[workspace.metadata]
# TODO: Fill in the projects metadata (which binary is what)

[workspace.dependencies]
prun = { version = "*" }
