[workspace]
members = [
	"Elements/Echo",
	"Elements/Mountain",
	"Elements/River",
	"Elements/Sun",
]
resolver = "2"
exclude = ["Vanilla/Microsoft/VSCode/cli"]

[workspace.package]
authors = ["ğŸ–‹ï¸â€Sourceâ€â€”â€ğŸ‘ğŸ»â€Openâ€â€” <Source/Open@Editor.Land>"]
documentation = "HTTPS://Documentation.Editor.Land"
edition = "2021"
homepage = "HTTPS://Editor.Land/"
license-file = "SEE LICENSE IN LICENSE"
publish = false
readme = "README.md"
repository = "HTTPS://GitHub.Com/CodeEditorLand/EcoSystem"

[workspace.metadata]
# TODO: Fill in the projects metadata (which binary is what)
